### ISSUE TITLE
trouble accessing EC2 example data

### ISSUE THREAD

**Issue by blimuld** [thunder-project/thunder#115]
Hello thunder team, 

apologies if this is a novice user error but I wanted to look at the example designmatrix for regression analysis and tried:

data, designmatrix = tsc.loadExampleEC2('zebrafish-optomotor-response') per the response to issue #17 however I receive an error regarding access keys matching s3n urls.

Please let me know if there is something I have wrong. I seem to be connecting to EC2 successfully and have tried uninstalling and re-installing thunder.  

Thank You!

---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-1-7ba1b25751f4> in <module>()
----> 1 data, designmatrix = tsc.loadExampleEC2('zebrafish-optomotor-response')

/root/thunder/python/thunder/utils/context.pyc in loadExampleEC2(self, dataset)
    546                                    nkeys=3)
    547             paramFile = self._sc.textFile("s3n://" + path + "params.json")
--> 548             params = json.loads(paramFile.first())
    549             modelFile = asarray(params['trials'])
    550             return data, modelFile

/root/spark/python/pyspark/rdd.py in first(self)
   1165         2
   1166         """
-> 1167         return self.take(1)[0]
   1168 
   1169     def saveAsNewAPIHadoopDataset(self, conf, keyConverter=None, valueConverter=None):

/root/spark/python/pyspark/rdd.py in take(self, num)
   1124         """
   1125         items = []
-> 1126         totalParts = self._jrdd.partitions().size()
   1127         partsScanned = 0
   1128 

/root/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py in __call__(self, *args)
    536         answer = self.gateway_client.send_command(command)
    537         return_value = get_return_value(answer, self.gateway_client,
--> 538                 self.target_id, self.name)
    539 
    540         for temp_arg in temp_args:

/root/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    298                 raise Py4JJavaError(
    299                     'An error occurred while calling {0}{1}{2}.\n'.
--> 300                     format(target_id, '.', name), value)
    301             else:
    302                 raise Py4JError(

Py4JJavaError: An error occurred while calling o29.partitions.
: java.lang.IllegalArgumentException: AWS Access Key ID and Secret Access Key must be specified as the username or password (respectively) of a s3n URL, or by setting the fs.s3n.awsAccessKeyId or fs.s3n.awsSecretAccessKey properties (respectively).
	at org.apache.hadoop.fs.s3.S3Credentials.initialize(S3Credentials.java:66)
	at org.apache.hadoop.fs.s3native.Jets3tNativeFileSystemStore.initialize(Jets3tNativeFileSystemStore.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:82)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:59)
	at org.apache.hadoop.fs.s3native.$Proxy7.initialize(Unknown Source)
	at org.apache.hadoop.fs.s3native.NativeS3FileSystem.initialize(NativeS3FileSystem.java:216)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:1386)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:66)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:1404)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:254)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:187)
	at org.apache.hadoop.mapred.FileInputFormat.listStatus(FileInputFormat.java:176)
	at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:208)
	at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:179)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:204)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:202)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:202)
	at org.apache.spark.rdd.MappedRDD.getPartitions(MappedRDD.scala:28)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:204)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:202)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:202)
	at org.apache.spark.api.java.JavaRDDLike$class.partitions(JavaRDDLike.scala:50)
	at org.apache.spark.api.java.JavaRDD.partitions(JavaRDD.scala:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:207)
	at java.lang.Thread.run(Thread.java:745)

**Comment by freeman-lab** [comment]
Hi @blimuld thanks for reporting this! I'm not certain, but I think this might be related to this issue, which was just recently reported and fixed https://github.com/thunder-project/thunder/issues/109. Depending on when you were running this, it could be you were hitting the same problem (the error message looked the same).

So you might try reinstalling your local version of thunder, and launching a new cluster. It's a good idea to uninstall before reinstalling, so do:

```
pip uninstall thunder-python
pip install thunder-python
```

But something else might be up, so maybe give that a try and let us know if it fixes it.

**Comment by andrewgiessel** [comment]
@blimuld  Any update here?  Does a recent version of thunder solve this issue?  Looking to close, thanks.
