### ISSUE TITLE
SSL times out pulling from S3

### ISSUE THREAD

**Issue by npyoung** [thunder-project/thunder#125]
I'm getting these errors when running

```python
tsc.convertImagesToSeries(vol_path, vol_path + '/series', dims=(48,2048,1184), inputFormat='stack', dtype='uint16', blockSize="150M", shuffle=True, overwrite=False)
```

It looks like it's timing out when reading from S3. I increased boto's http timeout, but it didn't help. Can something be done at the Thunder level to set the SSL timeout, load things in chunks, or perhaps try-catch-retry?

```
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/root/spark-1.2.1-bin-hadoop2.4/python/pyspark/worker.py", line 107, in main
    process()
  File "/root/spark-1.2.1-bin-hadoop2.4/python/pyspark/worker.py", line 98, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/root/spark-1.2.1-bin-hadoop2.4/python/pyspark/rdd.py", line 2081, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "/root/spark-1.2.1-bin-hadoop2.4/python/pyspark/rdd.py", line 2081, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "/root/spark-1.2.1-bin-hadoop2.4/python/pyspark/rdd.py", line 258, in func
    return f(iterator)
  File "/root/spark-1.2.1-bin-hadoop2.4/python/pyspark/rdd.py", line 1571, in combineLocally
    merger.mergeValues(iterator)
  File "/root/spark-1.2.1-bin-hadoop2.4/python/pyspark/shuffle.py", line 252, in mergeValues
    for k, v in iterator:
  File "/usr/local/lib/python2.7/dist-packages/thunder_python-0.4.1-py2.7.egg/thunder/rdds/fileio/readers.py", line 306, in readSplitFromS3
    buf = key.get_contents_as_string()
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1780, in get_contents_as_string
    response_headers=response_headers)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1648, in get_contents_to_file
    response_headers=response_headers)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1480, in get_file
    query_args=None)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1533, in _get_file_internal
    for bytes in self:
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 386, in next
    data = self.resp.read(self.BufferSize)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 413, in read
    return http_client.HTTPResponse.read(self, amt)
  File "/usr/lib/python2.7/httplib.py", line 567, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 341, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)
SSLError: The read operation timed out
```

**Comment by broxtronix** [comment]
I also frequently encounter this issue when loading large volumes from S3.  It causes load times to be significantly longer than they would otherwise be because a small number of S3 requests hang waiting for their HTTPS connections to time out.  

This issue appears to be at least somewhat widespread, and probably a boto or Amazon S3 bug, depending on how you look at it:

https://github.com/boto/boto/issues/2409

My feeling is that this bug is related to the size of the download and the frequency of access.  Perhaps we are triggering some sort of rate-limiting feature is Amazon S3 when we are loading many large volumes concurrently.

I've seen a few related issues in boto, and their solutions might be worth trying... one here suggests querying for the specific region where the bucket is stored, and then connecting to it directly:

https://github.com/boto/boto/issues/2207

Has anyone else noticed this issue?

**Comment by npyoung** [comment]
boto/boto#2207 looks like an upload issue, not a download issue.

**Comment by freeman-lab** [comment]
Thanks for flagging this @npyoung and @broxtronix , definitely sounds like a frustrating and pretty reproducible problem.

If it's related to the frequency of access rather than the size of the chunks per se, it might be worth trying to use fewer partitions. Specifically, when calling  `loadImages` or `convertImagesToSeries` methods or the like, you can specify an `npartitions` argument. In the loading operation [here](https://github.com/thunder-project/thunder/blob/master/python/thunder/rdds/fileio/readers.py#L334-L342), we open one boto connection per partition, and then iterate over key-value pairs within a partition. For a large number of volumes, using fewer partitions might throttle the effective frequency of access?

If that doesn't help, I'd support adding a try-retry-catch loop on the `get_contents_as_string` call. @npyoung want to try adding that and see if it helps? That'd be a super useful test.

Ultimately, for these kinds of files, we may want to rework the guts to use the Hadoop API rather than relying on boto (the new Spark method `binaryFiles` might be useful here). We could keep the existing image parsing code, and just rework the back side. But that will take some work, so would be great to improve the current situation if we can.

**Comment by npyoung** [comment]
The error was coming up in a cluster I have running on terminal.com's service. I switched to just using the` thunder-ec2 launch` script and I got a handful of SSL errors, but the jobs completed after a few minutes. Both clusters were of similar size, I think I was just getting way faster S3 connection speeds in EC2 (clocked the difference at about 2.5x). If I end up using terminal.com again I'll try out lowering `npartitions`.
