### ISSUE TITLE
Anaconda install pssh error when using thunder-ec2

### ISSUE THREAD

**Issue by sophie63** [thunder-project/thunder#231]
I am blocked on accessing EC2 with thunder-ec2. I have been consistently getting a pssh error at the Anaconda installation step (see below). I have restarted using --resume many times, redid the AWS credentials and key setup steps and also freshly pip installed thunder-python --upgrade but still get the error.
'''
[Generating cluster's SSH key on master]
[success]
[Transferring cluster's SSH key to slaves]
[success]
[Deploying files to master]
[success]
[Installing Spark (may take several minutes)]
[success]
[Downloading Anaconda]
[success]
[Installing Anaconda]
[SSH failure, returning error]
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/thunder/utils/ec2.py", line 514, in <module>
install_anaconda(master, opts)
File "/usr/local/lib/python2.7/dist-packages/thunder/utils/ec2.py", line 172, in install_anaconda
ssh(master, opts, "pssh -h /root/spark-ec2/slaves 'echo 'export "
File "/usr/local/lib/python2.7/dist-packages/thunder/utils/ec2.py", line 295, in ssh
raise Exception(stdout)
Exception: bash: pssh: command not found
'''

**Comment by sophie63** [comment]
I am using spark version 1.1.0.

**Comment by npyoung** [comment]
It looks like you're missing the pssh utility on the cluster master. Try to reproduce this error (just to get your cluster alive), then `thunder-ec2 login <your-cluster>` to log into the master. Once there, do `yum install -y pssh`. If that works, log out and try to start the cluster again with `--resume`.

**Comment by freeman-lab** [comment]
I wonder if it's an issue of an older AMI getting used that doesn't have `pssh`, though I'm fairly certain we've been using `pssh` in the launch process since before 1.1.0.

**Comment by sophie63** [comment]
I installed spark 1.4.1 instead of 1.1.0 and I don't have this problem anymore.
So maybe it would be helpful to update the documentation to say that 1.4 or higher is recommended for thunder-ec2.
Thanks to you both!

**Comment by sophie63** [comment]
Just FYI, I reproduce the problem with spark 1.2.1 but not 1.3.0. So you could recommend spark 1.3 or higher.
