### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by ObadaM** [thunder-project/thunder#327]
I am getting an error after running this line

data = td.images.fromexample('mouse',None)

```
Traceback (most recent call last):
File "/home/l-01-314/PycharmProjects/test/Motion_Correction.py", line 12, in 
data = td.images.frombinary(path=path, npartitions=1, order='F', engine=None)
File "/usr/anaconda3/lib/python3.5/site-packages/thunder/images/readers.py", line 255, in frombinary
buf = reader.read(path, filename=conf).decode('utf-8')
File "/usr/anaconda3/lib/python3.5/site-packages/thunder/readers.py", line 498, in read
storageScheme, key = self.getkey(path, filename=filename)
File "/usr/anaconda3/lib/python3.5/site-packages/thunder/readers.py", line 465, in getkey
scheme, keys = self.getkeys(path, filename=filename)
File "/usr/anaconda3/lib/python3.5/site-packages/thunder/readers.py", line 438, in getkeys
bucket = conn.get_bucket(bucket_name)
File "/usr/anaconda3/lib/python3.5/site-packages/boto/s3/connection.py", line 503, in get_bucket
return self.head_bucket(bucket_name, headers=headers)
File "/usr/anaconda3/lib/python3.5/site-packages/boto/s3/connection.py", line 522, in head_bucket
response = self.make_request('HEAD', bucket_name, headers=headers)
File "/usr/anaconda3/lib/python3.5/site-packages/boto/s3/connection.py", line 665, in make_request
retry_handler=retry_handler
File "/usr/anaconda3/lib/python3.5/site-packages/boto/connection.py", line 1071, in make_request
retry_handler=retry_handler)
File "/usr/anaconda3/lib/python3.5/site-packages/boto/connection.py", line 1030, in mexe
raise ex
File "/usr/anaconda3/lib/python3.5/site-packages/boto/connection.py", line 943, in mexe
request.body, request.headers)
File "/usr/anaconda3/lib/python3.5/http/client.py", line 1083, in request
self._send_request(method, url, body, headers)
File "/usr/anaconda3/lib/python3.5/http/client.py", line 1128, in _send_request
self.endheaders(body)
File "/usr/anaconda3/lib/python3.5/http/client.py", line 1079, in endheaders
self._send_output(message_body)
File "/usr/anaconda3/lib/python3.5/http/client.py", line 911, in _send_output
self.send(msg)
File "/usr/anaconda3/lib/python3.5/http/client.py", line 854, in send
self.connect()
File "/usr/anaconda3/lib/python3.5/http/client.py", line 1237, in connect
server_hostname=server_hostname)
File "/usr/anaconda3/lib/python3.5/ssl.py", line 376, in wrap_socket
_context=self)
File "/usr/anaconda3/lib/python3.5/ssl.py", line 747, in __init
self.do_handshake()
File "/usr/anaconda3/lib/python3.5/ssl.py", line 983, in do_handshake
self._sslobj.do_handshake()
File "/usr/anaconda3/lib/python3.5/ssl.py", line 628, in do_handshake
self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)
```

**Comment by boazmohar** [comment]
@ObadaM after fixing what I think is an unrelated error with PR #329, I was able to read the mouse example data. Is this still an issue?

**Comment by ObadaM** [comment]
@boazmohar I have just checked it and it is solved. Thanks!
