### ISSUE TITLE
Exception: IndexError: list index out of range when installing thunder on Ubuntu 14.04

### ISSUE THREAD

**Issue by mobcdi** [thunder-project/thunder#330]
After running sudo sudo pip install thunder-python on Ubuntu 14.04 with python 2.7.6 I get the error

```
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1091, in prepare_files
    req_to_install.check_if_exists()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 811, in check_if_exists
    self.satisfied_by = pkg_resources.get_distribution(self.req)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 535, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 415, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
IndexError: list index out of range
```
It appears to be some clean up processing that errors but when I try to `import thunder`
pip.log file is attached 
[pip_log.txt](https://github.com/thunder-project/thunder/files/304658/pip_log.txt)

 in python

**Comment by mheppner** [comment]
What version of pip are you using?

**Comment by mobcdi** [comment]
`pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)`

**Comment by mheppner** [comment]
Latest version of pip is 8.1.2. Try upgrading with `sudo pip install -U pip`.

**Comment by mobcdi** [comment]
Running `sudo pip install -U pip` followed by `sudo -H pip install thunder-python` worked. I was able to ```
>>> import thunder
>>> thunder.__version__
'1.1.0'
```
