### ISSUE TITLE
failure loading thunder on python 2.6

### ISSUE THREAD

**Issue by industrial-sloth** [thunder-project/thunder#97]
Launching using the current master branch of thunder fails on python 2.6 with the following error:

```
Traceback (most recent call last):
  File "./bin/thunder", line 3, in <module>
    import thunder
  File "/root/thunder/python/thunder/__init__.py", line 13, in <module>
    from thunder.imgprocessing.registration import Registration, RegistrationModel
  File "/root/thunder/python/thunder/imgprocessing/registration.py", line 233
    transformations = {int(k): transClass(**v) for k, v in input['transformations'].iteritems()}
                                                 ^
SyntaxError: invalid syntax
```

Dictionary comprehensions were only introduced in python 2.7. 

This affects the `thunder-ec2` script, which launches the basic spark AMIs (which have python 2.6 installed) and pulls in the current head of master.

**Comment by freeman-lab** [comment]
@industrial-sloth great, thanks for catching this!
